import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {Orders,default as worker} from '../server/worker.mjs';
import {PRODUCTS,CATALOG_VERSION} from '../server/catalog.mjs';
import {orderNumber,newOrderEmails,reportEmail} from '../server/email.mjs';
const core=globalThis.OrderCore;
const env={ADMIN_EMAIL:'iad.og.2022@gmail.com',STOREFRONT_URL:'https://iadshop.github.io/IAD.SHOP/',BANK_NAME:'永豐',BANK_CODE:'807',BANK_HOLDER:'測試',BANK_ACCOUNT:'123',BUYER_EMAIL_ENABLED:'false',MAIL_RELAY_URL:'https://example.invalid/exec',MAIL_RELAY_SECRET:'test-only',ALLOWED_ORIGINS:'https://iadshop.github.io',ADMIN_TOKEN:'test-admin'};
function setup(){const db=new DatabaseSync(':memory:');let alarms=[];const sql={exec(query,...args){const stmt=db.prepare(query);return {toArray:()=>stmt.all(...args)};}};
 // Cloudflare exec runs immediately; adapt SQLite statements, preserving real transactions.
 sql.exec=(query,...args)=>{const stmt=db.prepare(query);if(/^\s*(SELECT|PRAGMA)/i.test(query))return {toArray:()=>stmt.all(...args)};stmt.run(...args);return {toArray:()=>[]};};
 const ctx={storage:{sql,transactionSync(fn){db.exec('BEGIN');try{const value=fn();db.exec('COMMIT');return value;}catch(e){db.exec('ROLLBACK');throw e;}},setAlarm:async v=>alarms.push(v)}};
 return {service:new Orders(ctx,env),db,ctx};}
function payload(){const p=PRODUCTS[0],items=[{productId:p.id,season:p.season,color:p.colors[0]||'',size:p.sizes[0]||'',quantity:1}];return {requestId:crypto.randomUUID(),accessToken:'a'.repeat(64),catalogVersion:CATALOG_VERSION,items,contact:{name:'測試買家',phone:'0912345678',email:'buyer@example.com'},delivery:{method:'STORE',receiverName:'測試',receiverPhone:'0912345678',storeType:'SEVEN_ELEVEN',storeName:'測試店',storeCode:'123456'},paymentMethod:'BANK_TRANSFER',buyerNote:'測試勿出貨',expectedTotal:core.quote(items,PRODUCTS,'STORE').total};}
test('global sequence begins at 088 and persists across object recreation and dates',async()=>{const {service,ctx,db}=setup(),p=payload();const first=await service.perform('createOrder',p);assert.match(first.orderId,/-088$/);const second=await new Orders(ctx,env).perform('createOrder',{...p,requestId:crypto.randomUUID()});assert.match(second.orderId,/-089$/);assert.equal(db.prepare('SELECT value FROM counter').get().value,89);assert.equal(orderNumber(90,new Date('2026-10-08T16:00:00Z')),'IAD-2026-1009-090');});
test('simultaneous requests and retry create one row and one notification; reject reused id with changed contents',async()=>{const {service,db}=setup(),p=payload();const result=await Promise.all(Array.from({length:12},()=>service.perform('createOrder',p)));assert.equal(new Set(result.map(o=>o.orderId)).size,1);assert.equal(db.prepare('SELECT count(*) AS n FROM orders').get().n,1);assert.equal(db.prepare('SELECT count(*) AS n FROM outbox').get().n,1);await assert.rejects(()=>service.perform('createOrder',{...p,buyerNote:'changed'}),e=>e.code==='IDEMPOTENCY_CONFLICT');});
test('server price, options, email and required fields validated before sequence allocation',async()=>{const {service,db}=setup(),p=payload();for(const bad of [{expectedTotal:1},{catalogVersion:'old'},{contact:{...p.contact,email:'invalid'}},{items:[{...p.items[0],size:'fake'}]}])await assert.rejects(()=>service.perform('createOrder',{...p,...bad}));assert.equal(db.prepare('SELECT value FROM counter').get().value,87);});
test('private lookup requires correct capability; reports deduplicate and never imply PAID',async()=>{const {service,db}=setup(),p=payload(),o=await service.perform('createOrder',p);await assert.rejects(()=>service.perform('getOrder',{orderId:o.orderId,accessToken:'b'.repeat(64)}));const report={orderId:o.orderId,accessToken:p.accessToken,reportRequestId:crypto.randomUUID(),reference:'12345',paidAt:'2026-10-08T05:00:00Z',note:'test',amount:o.total};await assert.rejects(()=>service.perform('reportPayment',{...report,amount:1}));await assert.rejects(()=>service.perform('reportPayment',{...report,paidAt:''}));let r=await service.perform('reportPayment',report);assert.equal(r.paymentStatus,'PAYMENT_REPORTED');assert.equal(r.contact,undefined);await service.perform('reportPayment',report);assert.equal(db.prepare('SELECT count(*) AS n FROM reports').get().n,1);assert.equal(db.prepare('SELECT count(*) AS n FROM outbox').get().n,2);const paid=JSON.parse(db.prepare('SELECT data FROM orders').get().data);paid.paymentStatus='PAID';db.prepare('UPDATE orders SET data=?').run(JSON.stringify(paid));await assert.rejects(()=>service.perform('reportPayment',{...report,reportRequestId:crypto.randomUUID()}),e=>e.code==='ORDER_CLOSED');});
test('cash deposit requires reconciliation note and payment time',async()=>{const {service}=setup(),p={...payload(),paymentMethod:'CASH_DEPOSIT'},o=await service.perform('createOrder',p),r={orderId:o.orderId,accessToken:p.accessToken,reportRequestId:crypto.randomUUID(),amount:o.total,paidAt:'2026-10-08T05:00:00Z',note:''};await assert.rejects(()=>service.perform('reportPayment',r));assert.equal((await service.perform('reportPayment',{...r,note:'ATM交易序號123'})).paymentStatus,'PAYMENT_REPORTED');});
test('outbox failure retains order; retry sends once and persistence marks success',async()=>{const {service,db}=setup(),p=payload(),original=globalThis.fetch;try{await service.perform('createOrder',p);let calls=0;globalThis.fetch=async()=>{calls++;throw new Error('timeout');};await service.alarm();assert.equal(db.prepare('SELECT state FROM outbox').get().state,'PENDING');assert.equal(db.prepare('SELECT count(*) AS n FROM orders').get().n,1);globalThis.fetch=async()=>{calls++;return Response.json({ok:true});};await service.alarm();await service.alarm();assert.equal(calls,2);assert.equal(db.prepare('SELECT state FROM outbox').get().state,'SENT');}finally{globalThis.fetch=original;}});
test('email subjects, full items, shipping, bank info and future buyer link',async()=>{const {service}=setup(),p=payload(),o=await service.perform('createOrder',p),full={...o,contact:p.contact,delivery:p.delivery,buyerNote:p.buyerNote};const emails=newOrderEmails(full,p.accessToken,env);assert.ok(emails[0].subject.startsWith('[IAD SHOP 新訂單] IAD-'));assert.ok(emails[0].text.includes(p.contact.email));assert.ok(emails[0].text.includes('單價'));assert.ok(emails[1].text.includes('先付款後出貨'));assert.equal(new URL(emails[1].button.url).hash.includes('token='),true);assert.ok(reportEmail(full,{amount:o.total,paidAt:new Date().toISOString(),createdAt:new Date().toISOString(),reference:'12345',note:''},env).subject.startsWith('[IAD SHOP 付款回報]'));});
test('CORS and admin authorization fail closed; no browser can forge admin actions',async()=>{const blocked=await worker.fetch(new Request('https://api/orders',{method:'POST',headers:{Origin:'https://evil.invalid'},body:'{}'}),env);assert.equal(blocked.status,403);const admin=await worker.fetch(new Request('https://api/admin',{method:'POST',body:'{}'}),env);assert.equal(admin.status,401);const forged=await worker.fetch(new Request('https://api/orders',{method:'POST',headers:{Origin:'https://iadshop.github.io'},body:JSON.stringify({action:'adminStatus'})}),env);assert.equal(forged.status,400);});
test('shipping thresholds unchanged; all four methods supported',()=>{assert.equal(core.shipping(598,'STORE'),70);assert.equal(core.shipping(599,'STORE'),0);assert.equal(core.shipping(1498,'HOME'),150);assert.equal(core.shipping(1499,'HOME'),0);assert.deepEqual(core.paymentMethods,['BANK_TRANSFER','CASH_DEPOSIT','CREDIT_CARD','LINE_PAY']);});
import fs from 'node:fs';
import vm from 'node:vm';
test('Gmail relay rejects wrong secret or recipient and deduplicates retries without Sheets',()=>{
 const props=new Map([['RELAY_SECRET','test-secret']]);let mails=0;
 const context={JSON,Date,LockService:{getScriptLock:()=>({tryLock:()=>true,releaseLock(){}})},PropertiesService:{getScriptProperties:()=>({getProperty:k=>props.get(k),setProperty:(k,v)=>props.set(k,v),getProperties:()=>Object.fromEntries(props),deleteProperty:k=>props.delete(k)})},MailApp:{getRemainingDailyQuota:()=>100,sendEmail:()=>mails++},ContentService:{MimeType:{JSON:'json'},createTextOutput:v=>({setMimeType:()=>v})}};
 vm.createContext(context);vm.runInContext(fs.readFileSync('server/GmailRelay.gs','utf8'),context);
 const p={secret:'test-secret',key:'IAD-2026-1008-088-new-0',message:{to:'iad.og.2022@gmail.com',subject:'Test',text:'Synthetic data'}};
 const call=p=>JSON.parse(context.doPost({postData:{contents:JSON.stringify(p)}}));
 assert.equal(call({...p,secret:'wrong'}).ok,false);assert.equal(call({...p,message:{...p.message,to:'buyer@example.com'}}).ok,false);
 assert.equal(call(p).ok,true);assert.equal(call(p).ok,true);assert.equal(mails,1);
 assert.equal(fs.readFileSync('server/GmailRelay.gs','utf8').includes('SpreadsheetApp.'),false);
});
